[project]
name = "openbudget"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.128.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
